# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

inhibit_all_warnings!

target 'GPAQuery' do
pod 'Charts'
pod 'VGParallaxHeader'
pod 'MBProgressHUD'
pod 'AFNetworking'
pod 'DGActivityIndicatorView'
pod 'JXLS'
pod 'REMenu'
end

target 'GPAQueryTests' do

end

target 'GPAQueryUITests' do

end

